export const marketName = [
  { id: 1446, translationKey: "market.game_lines_spread" },
  { id: 1450, translationKey: "market.game_lines_total" },
  { id: 163, translationKey: "market.home_team_total_points" },
  { id: 164, translationKey: "market.away_team_total_points" },
  { id: 2021, translationKey: "market.home_team_total_incl_ot" },
  { id: 2022, translationKey: "market.away_team_total_incl_ot" },
  { id: 180079, translationKey: "market.q1_lines_spread" },
  { id: 180080, translationKey: "market.q1_lines_total" },
  { id: 759, translationKey: "market.q1_home_total" },
  { id: 760, translationKey: "market.q1_away_total" },
  { id: 180077, translationKey: "market.q1_moneyline" },
  { id: 180078, translationKey: "market.q1_moneyline" },
  { id: 180753, translationKey: "market.h1_spread" },
  { id: 180062, translationKey: "market.h1_total" },
  { id: 584, translationKey: "market.h1_home_total" },
  { id: 768, translationKey: "market.h1_away_total" },
  { id: 180060, translationKey: "market.h1_moneyline" },
  { id: 180097, translationKey: "market.q3_lines_spread" },
  { id: 18098, translationKey: "market.q3_lines_total" },
  { id: 533, translationKey: "market.q3_home_total" },
  { id: 764, translationKey: "market.q3_away_total" },
  { id: 180095, translationKey: "market.q3_moneyline" },
  { id: 180096, translationKey: "market.q3_moneyline" },
  { id: 180104, translationKey: "market.q4_moneyline" },
];
